#include <bits/stdc++.h>
using namespace std;

//Time complextiy :- O(n)
// Space complexity :- O(n)

// Approach :-  
// for solving these problem instead of generating all the subsequences
// we can use find the sequence generated at each level which will be 2*times_of_previous_level
// at ever level we've to substract the duplicates generated by the previous level 
// if a char repeats again it will generate duplicate
// the number of duplicates will be the total number of subsequences generated at the previous level of the last occurence of that char - 1 index 
// we can store the last occurence of each char in a map 
// why previous char ind - 1 gives the duplicate count 
// because the subsequence generated by take of that case will be same as genrated by current one 
// we can memoize the result of each level in a 1-dp array and return the final result at the end


//Link :- https://leetcode.com/problems/distinct-subsequences-ii/

class Solution {
private:
    int mod = 1e9+7;

    int solve(int num, vector<int> &dp, vector<int> &prev){
        if(num == 0)
            return 1;
        
        if(dp[num] != -1)
            return dp[num];
        
        // general formula for the total number of subsequences generated at each level will be 2*times_of_previous_level
        int total = (solve(num-1, dp, prev) * 2 ) % mod;

        // substract the duplicates generated by the previous level if a char repeats again it will generate duplicate
        if(prev[num] != 0){
            int duplicates = solve(prev[num]-1, dp, prev);
            total = (total - duplicates + mod) % mod;
        }
        return dp[num] = total;
    }

public:
    int distinctSubseqII(string s) {
        int n = s.size();
        vector<int> lastInd(26, 0), prev(n+1, 0);
        
        // store the last occurence of each char in a map
        for(int i=1; i<=n; ++i){
            int ind = s[i-1] - 'a';
            prev[i] = lastInd[ind];
            lastInd[ind] = i;
        }
        vector<int> dp(n+1, -1);
        return (solve(n, dp, prev) - 1 + mod) % mod;
    }
};